// Server-side fetch of Ice's live GitHub contribution stats.
// Every source is public — no token required:
//   • stats.json  -> auto-generated by the icetrahan/icetrahan Actions workflow
//   • users/:u    -> public profile (for account age)
//   • contributions API -> public contribution calendar
// Cached for an hour via Next's fetch revalidation.

export type GhLang = {
  name: string;
  percentage: number;
  linesAdded: number;
  color: string;
};

export type GhDay = { date: string; count: number; level: number };

export type GitHubStats = {
  totalLinesAdded: number | null;
  totalCommits: number | null;
  totalRepos: number | null;
  yearsCoding: number;
  totalContributions: number | null;
  contributions: GhDay[];
  languages: GhLang[];
};

type RawLang = {
  name: string;
  lines_added?: number;
  percentage?: number;
  color?: string;
};

const STATS_URL =
  "https://raw.githubusercontent.com/icetrahan/icetrahan/main/stats.json";
const USER_URL = "https://api.github.com/users/icetrahan";
const CONTRIB_URL =
  "https://github-contributions-api.jogruber.de/v4/icetrahan?y=last";
const REVALIDATE = 3600;

export async function getGitHubStats(): Promise<GitHubStats | null> {
  try {
    const [statsRes, userRes, contribRes] = await Promise.all([
      fetch(STATS_URL, { next: { revalidate: REVALIDATE } }),
      fetch(USER_URL, {
        next: { revalidate: REVALIDATE },
        headers: { Accept: "application/vnd.github+json" },
      }),
      fetch(CONTRIB_URL, { next: { revalidate: REVALIDATE } }).catch(() => null),
    ]);

    if (!statsRes.ok) return null;

    const stats = await statsRes.json();
    const user = userRes.ok ? await userRes.json() : null;

    const createdYear = user?.created_at
      ? new Date(user.created_at).getFullYear()
      : 2014;
    const yearsCoding = Math.max(1, new Date().getFullYear() - createdYear);

    const languages: GhLang[] = (stats.languages ?? [])
      .filter((l: RawLang) => (l.percentage ?? 0) >= 0.1)
      .slice(0, 7)
      .map((l: RawLang) => ({
        name: l.name,
        percentage: l.percentage ?? 0,
        linesAdded: l.lines_added ?? 0,
        color: l.color ?? "#58e1ff",
      }));

    let totalContributions: number | null = null;
    let contributions: GhDay[] = [];
    if (contribRes && contribRes.ok) {
      const cd = await contribRes.json();
      totalContributions = cd?.total?.lastYear ?? null;
      contributions = (cd?.contributions ?? []).map((d: GhDay) => ({
        date: d.date,
        count: d.count,
        level: d.level,
      }));
    }

    return {
      totalLinesAdded: stats.total_lines_added ?? null,
      totalCommits: stats.total_commits ?? null,
      totalRepos: stats.total_repos_analyzed ?? null,
      yearsCoding,
      totalContributions,
      contributions,
      languages,
    };
  } catch {
    return null;
  }
}
